name: junitreporter_flutter_3x
version: 2.0.6
description: Generate JUnit XML reports from dart test runs. Transforms the output of dart or flutter tests to
  JUnit style XML

homepage: https://github.com/derteufelqwe/dart-junitreport
documentation:

dependencies:
  args: ^2.3.0
  intl: ^0.19.0
  testreport: ^2.0.1
  xml: ^6.5.0

dev_dependencies:
  test: any
  lints: 1.0.1

environment:
  sdk: '>=3.0.0 <3.9.0'

executables:
  tojunit:
